#!/bin/bash
#
# This script builds cities program.
#
set -euo pipefail

if ! which go-bindata > /dev/null; then
  echo "Oivey, we don't have go-bindata! Maybe you're in prod" >&2
  exit 1
fi

echo "I will package up html into bindata.go"
go-bindata html/

echo "I will compile the cities source coude"
go build

echo "Whasaaap! I will run the test"
go test

echo "Yo, I am generating cities.env file, man"
rm -f cities.env
echo "CITIES_ISPROD=true" >> cities.env
echo "CITIES_VERSION=$(./last_commit)" >> cities.env


