#!/bin/bash
#
# This script compiles and deploys cities program.
#
set -euo pipefail

echo "I will package up html into bindata.go"
go-bindata html/

echo "I will compile the cities source coude"
go build

echo "Whasaaap! I will run the test"
go test

echo "Yo, I am generating cities.env file, man"
rm -f cities.env
echo "CITIES_ISPROD=true" >> cities.env
echo "CITIES_VERSION=$(./last_commit)" >> cities.env

echo "Stopping ye olde server"
sudo systemctl stop cities

echo "Whasaap! Copying files to target directory"
sudo cp cities cities.env /etc/cities/

echo "Hurray, restarting the server!"
sudo systemctl restart cities


