#!/bin/bash
#
# This script deploys cities program.
#
set -euo pipefail

echo "Bonjour, I will check if cities and cities.env exist"
if [[ ! -e cities ]] || [[ ! -e cities.env ]]; then
  echo "Oivey, cities or cities.env does not exist!!"
  exit 1
fi

echo "Stopping ye olde server"
sudo systemctl stop cities

echo "Whasaap! Copying files to target directory"
sudo cp cities cities.env /etc/cities/

echo "Hurray, restarting the server!"
sudo systemctl restart cities


