#!/bin/bash
#
# This script sends messages to slack.
#
set -euo pipefail

declare MESSAGE="${1:-}"
declare SLACKAPIKEY="${SLACKAPIKEY:-}" 

source slack.env

if [[ "$#" -ne 1 ]]; then
  echo "Usage is $0 'Yo Mo'"
  exit 1
fi

# NOTE: if the SLACKAPIKEY is invalid slack returns 302 Found.
# It would be nice to detect this case and return with failure status.
echo "Yo, I will send a message '$MESSAGE' to slack"
curl -H 'Content-type: application/json' \
     --data "{\"text\":\"$MESSAGE\"}" \
     https://hooks.slack.com/services/$SLACKAPIKEY
echo
echo "Howdy, I have sent to https://hooks.slack.com/services/$SLACKAPIKEY"

