#!/bin/bash
#
# This script sends messages to slack.
#
set -euo pipefail

declare MESSAGE="${1:-}"
declare SLACKAPIKEY="${SLACKAPIKEY:-}" 
declare RESPONSE=""

source slack.env

if [[ "$#" -ne 1 ]]; then
  echo "Usage is $0 'Yo Mo'" >&2
  exit 1
fi

echo "Yo, I will send a message '$MESSAGE' to slack"
RESPONSE=$(curl -s -H 'Content-type: application/json' \
                --data "{\"text\":\"$MESSAGE\"}" \
                https://hooks.slack.com/services/$SLACKAPIKEY)

if [[ "$RESPONSE" != "ok" ]]; then
  echo "gotty this response '$RESPONSE'"
  echo "Yo, methinks there is an issue with slack message" >&2
  exit 1
fi
echo
echo "Howdy, I have sent to https://hooks.slack.com/services/$SLACKAPIKEY"

